function y = test2(x)
%TEST2 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and DSP System Toolbox 23.2.
% Generated on: 07-Oct-2023 14:19:42

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % Equiripple FIR Lowpass filter designed using the FIRPM function.
    %
    % % All frequency values are in Hz.
    % Fs = 48000;  % Sampling Frequency
    %
    % Fpass = 9600;            % Passband Frequency
    % Fstop = 12000;           % Stopband Frequency
    % Dpass = 0.057501127785;  % Passband Ripple
    % Dstop = 0.0001;          % Stopband Attenuation
    % dens  = 16;              % Density Factor
    %
    % % Calculate the order from the parameters using FIRPMORD.
    % [N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);
    %
    % % Calculate the coefficients using the FIRPM function.
    % b  = firpm(N, Fo, Ao, W, {dens});
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [-0.000919098208468256 -0.0027176960265955 ...
        -0.00248695275983231 0.00366143838350709 0.0136509252306624 ...
        0.0173511659010933 0.00766530619042168 -0.0065547188696424 ...
        -0.00769678403706536 0.00610545942139436 0.0138739157486354 ...
        0.00035086172829091 -0.0169089254366905 -0.00890564274915868 ...
        0.0174411295008549 0.0207450445276099 -0.0122964942519403 ...
        -0.0342408659095784 -0.0010345296055724 0.0477903055208015 ...
        0.027363037914848 -0.0593795188310466 -0.0823070259292291 ...
        0.0671869094328705 0.310015177090251 0.430047880343517 0.310015177090251 ...
        0.0671869094328705 -0.0823070259292291 -0.0593795188310466 ...
        0.027363037914848 0.0477903055208015 -0.0010345296055724 ...
        -0.0342408659095784 -0.0122964942519403 0.0207450445276099 ...
        0.0174411295008549 -0.00890564274915868 -0.0169089254366905 ...
        0.00035086172829091 0.0138739157486354 0.00610545942139436 ...
        -0.00769678403706536 -0.0065547188696424 0.00766530619042168 ...
        0.0173511659010933 0.0136509252306624 0.00366143838350709 ...
        -0.00248695275983231 -0.0027176960265955 -0.000919098208468256]);
end

y = step(Hd,double(x));


% [EOF]
